### ISSUE TITLE
HW requirements

### ISSUE THREAD

**Issue by kaishijeng** [via-intelligent-vision/VIA-AI#1]
Can I run your android app without comma.ai Panda and Giraffe? Just use it like an advanced dashcam.
If yes, what features are enabled in your app?

Thanks,

**Comment by AudiChang** [comment]
If you want to run without canbus data, lane departure warning and video recording features can be enabled.

**Comment by kaishijeng** [comment]
Tried to build apk with android studio and got the following error:

Build command failed.
Error while executing process C:\Users\tjc\AppData\Local\Android\Sdk\cmake\3.6.4111459\bin\cmake.exe with arguments {--build C:\Users\tjc\Downloads\VIA-AI-master\System\AutomotiveKernel\.externalNativeBuild\cmake\debug\arm64-v8a --target VIA-AI}
[1/1] Linking CXX shared library C:\Users\tjc\Downloads\VIA-AI-master\System\AutomotiveKernel\build\intermediates\cmake\debug\obj\arm64-v8a\libVIA-AI.so
FAILED: cmd.exe /C "cd . && C:\Users\tjc\AppData\Local\Android\Sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe  --target=aarch64-none-linux-android21 --gcc-toolchain=C:/Users/tjc/AppData/Local/Android/Sdk/ndk-bundle/toolchains/aarch64-linux-android-4.9/prebuilt/windows-x86_64 --sysroot=C:/Users/tjc/AppData/Local/Android/Sdk/ndk-bundle/sysroot -fPIC -isystem C:/Users/tjc/AppData/Local/Android/Sdk/ndk-bundle/sysroot/usr/include/aarch64-linux-android -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -Wa,--noexecstack -Wformat -Werror=format-security -std=c++11  -std=c++11 -fexceptions -frtti -Werror=return-type -Wl,-Bsymbolic -O0 -fno-limit-debug-info  -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libatomic.a -nostdlib++ --sysroot C:/Users/tjc/AppData/Local/Android/Sdk/ndk-bundle/platforms/android-21/arch-arm64 -Wl,--build-id -Wl,--warn-shared-textrel -Wl,--fatal-warnings -LC:/Users/tjc/AppData/Local/Android/Sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/libs/arm64-v8a -Wl,--no-undefined -Wl,-z,noexecstack -Qunused-arguments -Wl,-z,relro -Wl,-z,now -shared -Wl,-soname,libVIA-AI.so -o C:\Users\tjc\Downloads\VIA-AI-master\System\AutomotiveKernel\build\intermediates\cmake\debug\obj\arm64-v8a\libVIA-AI.so @CMakeFiles/VIA-AI.rsp  && cd ."
CMakeFiles/VIA-AI.dir/jni_CameraCalibrator.cpp.o: In function `Java_com_viatech_camera_CameraCalibrator_jni_1save':

C:\Users\tjc\Downloads\VIA-AI-master\System\AutomotiveKernel\src\main\jni/jni_CameraCalibrator.cpp:190: undefined reference to `via::camera::CameraCalibrator::save(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&)'

CMakeFiles/VIA-AI.dir/jni_CameraCalibrator.cpp.o: In function `Java_com_viatech_camera_CameraCalibrator_jni_1findPattern_1NV12':

C:\Users\tjc\Downloads\VIA-AI-master\System\AutomotiveKernel\src\main\jni/jni_CameraCalibrator.cpp:238: undefined reference to `via::camera::CameraCalibrator::findPattern(unsigned char*, media::FrameFormatType, cv::Size_<int>, cv::Rect_<int>, std::__ndk1::vector<cv::Point_<float>, std::__ndk1::allocator<cv::Point_<float> > >*)'

CMakeFiles/VIA-AI.dir/jni_CameraCalibrator.cpp.o: In function `Java_com_viatech_camera_CameraCalibrator_jni_1findPattern_1BGR888':

C:\Users\tjc\Downloads\VIA-AI-master\System\AutomotiveKernel\src\main\jni/jni_CameraCalibrator.cpp:271: undefined reference to `via::camera::CameraCalibrator::findPattern(unsigned char*, media::FrameFormatType, cv::Size_<int>, cv::Rect_<int>, std::__ndk1::vector<cv::Point_<float>, std::__ndk1::allocator<cv::Point_<float> > >*)'

CMakeFiles/VIA-AI.dir/jni_CameraCalibrator.cpp.o: In function `Java_com_viatech_camera_CameraCalibrator_jni_1findPattern_1RGB888':

C:\Users\tjc\Downloads\VIA-AI-master\System\AutomotiveKernel\src\main\jni/jni_CameraCalibrator.cpp:300: undefined reference to `via::camera::CameraCalibrator::findPattern(unsigned char*, media::FrameFormatType, cv::Size_<int>, cv::Rect_<int>, std::__ndk1::vector<cv::Point_<float>, std::__ndk1::allocator<cv::Point_<float> > >*)'

CMakeFiles/VIA-AI.dir/jni_CameraCalibrator.cpp.o: In function `Java_com_viatech_camera_CameraCalibrator_jni_1findPattern_1ARGB888':

C:\Users\tjc\Downloads\VIA-AI-master\System\AutomotiveKernel\src\main\jni/jni_CameraCalibrator.cpp:329: undefined reference to `via::camera::CameraCalibrator::findPattern(unsigned char*, media::FrameFormatType, cv::Size_<int>, cv::Rect_<int>, std::__ndk1::vector<cv::Point_<float>, std::__ndk1::allocator<cv::Point_<float> > >*)'

CMakeFiles/VIA-AI.dir/jni_SensingModule.cpp.o: In function `Java_com_viatech_sensing_SensingModule_jni_1init':

C:\Users\tjc\Downloads\VIA-AI-master\System\AutomotiveKernel\src\main\jni/jni_SensingModule.cpp:240: undefined reference to `via::sensing::SensingComponent::init(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >&)'

CMakeFiles/VIA-AI.dir/jni_SensingModule.cpp.o: In function `Java_com_viatech_sensing_SensingModule_jni_1restoreConfiguration':

C:\Users\tjc\Downloads\VIA-AI-master\System\AutomotiveKernel\src\main\jni/jni_SensingModule.cpp:508: undefined reference to `via::sensing::SensingComponent::exportConfig(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >)'

automotiveControl/libautomotiveControl.a(AutomotiveController.cpp.o): In function `via::automotive::AutomotiveController::ControllerImpl::updatePlanners()':

C:\Users\tjc\Downloads\VIA-AI-master\System\AutomotiveKernel\src\main\jni\automotiveControl/AutomotiveController.cpp:614: undefined reference to `via::sensing::SensingComponent::exportConfig(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >)'

clang++.exe: error: linker command failed with exit code 1 (use -v to see invocation)

ninja: build stopped: subcommand failed.

**Comment by AudiChang** [comment]
Please use NDK r16 version to build this project.

**Comment by kaishijeng** [comment]
I am able to build apk with NDK r16.
Any particular mounter you can recommend?

Thanks

**Comment by AudiChang** [comment]
We use RAM mount phone holder to install smartphone. It's for your reference.

**Comment by kaishijeng** [comment]
Why does your SW need to do camera calibration?
COMMA.AI doesn't need this.

Thanks,

**Comment by AudiChang** [comment]
Comma.ai also need to calibration at first time. Please refer to openpilot website : https://community.comma.ai/wiki/index.php/First_OpenPilot_Drive

**Comment by kaishijeng** [comment]
Thanks for pointing this.
Does  commaai require to use checkerboard to do calibration?
If lane detection is deep-learning based, can calibration be avoided?

Thanks,

**Comment by AudiChang** [comment]
1. Neither of Comma.ai and VIAIA don't need checkerboard to do calibration.
2. Deep-learning based lane detection is one of method for calibrating, it also needs this process.

**Comment by kaishijeng** [comment]
I don't see camera calibration below mentioned in comma.ai openpilot.
https://github.com/via-intelligent-vision/VIA-AI/blob/master/Docs/ApplicationTutorial/Calibrations/CameraCalibration/README.md

By the way, does your SW work for any android phone as long as it is snapdragon 820-based?
Thanks,

**Comment by SimonPu-VIA** [comment]
1. I think because EON is a single platform, so it may do with the camera(lens) calibration in advance. But VIA.AI are relatively open for all android phone. So here the difficult know more what about the user's Camera or lens characteristics in advance. This is what we want users to be on own phone platform and calibration as distortion correction step with camera/lens.

2. Basically the code should be workable, but we have only verified and tested on these supported devices as mentioned as the page (https://github.com/via-intelligent-vision/VIA-AI#supported-devices)

**Comment by kaishijeng** [comment]
@SimonPu-VIA 

1) This makes sense.
2) I will try it with a different cell phone later. 

Thanks,

**Comment by AudiChang** [comment]
@kaishijeng 
I am sorry that I mix up the system calibration and camera calibration.
@SimonPu-VIA is right.

**Comment by kaishijeng** [comment]
Is your deep learning module source not open? I am not able to see which java code in this repository to call qualcomm snpe engine?
Which module has lane detection with camera input? It will be nice you can add an additional readme for this.

Thanks,

**Comment by AudiChang** [comment]
Yes, deep learning module source is not opened yet.
If you want to use lane detection with camera image input, please refer to onFrameReady() at "MainActivity.java". You can find camera2 dequeue buffer input yuv planes into mSensingModule_LDWS for setting image resource. The other member mSensingTask_LDWS is used for lane detecting with mSensingModule_LDWS resource.
We will try to add additional readme for this. Thanks for your suggestion.

**Comment by kaishijeng** [comment]
@AudiChang 

    Thanks for additional info of SensingModule. Do you have a plan to open deep learning module?

Thanks,

**Comment by AudiChang** [comment]
VIA.AI follows company policy. If VIA decides to open deep learning module will let you know.

**Comment by kaishijeng** [comment]
Thanks,

Kaishi

**Comment by kaishijeng** [comment]
@AudiChang 

I have done camera calibration. However, the system is stuck with non-calibrated screen when I start the app.
As I mentioned before, I don't have comma.ai panda & comma.ai giraffe because my car is not the type which can be used with panda/giraffe.
Is there a way to use rest of application features, like lane detection or lane departure warning without panda/giraffe? How to enable this mode?

Thanks

**Comment by kaishijeng** [comment]
@AudiChang @SimonPu-VIA 

Do you know any answer of my question?

Thanks,

**Comment by SimonPu-VIA** [comment]
@kaishijeng 
Do you have the process done of system calibration?

https://github.com/via-intelligent-vision/VIA-AI/blob/master/Docs/ApplicationTutorial/Calibrations/SystemCalibration/README.md

**Comment by kaishijeng** [comment]
@SimonPu-VIA 

I don't have comma.ai panda & comma.ai giraffe. So Step2 can not be done with my system.
When I started the dashcam app and press "start" button, I don't see 
CANBus status lamps is enable or not (shown as following image). 
The screen is stuck with Non Calibrated system as shown in Step 5.

**Comment by SimonPu-VIA** [comment]
I think It's because you don't have done of the system calibration. For the system calibration steps should be work also without comma.ai panda & comma.ai giraffe.

Regarding of the step5: When system calibration enabled, Please keep the vehicle driving on the center of lane and speed over 75km/h, don't change the lane if possible, system calibration will finish in the 30s ~ 2 minutes.

**Comment by kaishijeng** [comment]
@SimonPu-VIA 

It works after I do system calibration by pressing a button manually.
This step doesn't mention in the README
Your lan detection performance is quite good. I am using Xiaomi Note 7 for this test

Thanks,

**Comment by SimonPu-VIA** [comment]
Great to hear that your platform can be workable also. 
If there is no problem, let me close this question thread firstly. We are very welcome for discussion if you have any new questions and suggestions in the future.
